name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Verify Go environment
        run: go env

      - name: Install dependencies
        run: go mod tidy

      - name: Build Mbongo-Chain
        working-directory: ${{ github.workspace }}/cmd/mbongo-chain
        run: go build -v .

      - name: Run tests
        run: go test ./... -v
